#  Name of workflow
name: Production Workflow

on:
  pull_request:
    branches:
      - master
      - main
    types: [closed]

# Jobs to carry out
jobs:
  deploy:
    # this job will only run if the PR has been merged
    if: github.event.pull_request.merged == true
    # Operating system to run job on
    runs-on: ubuntu-latest
    # Steps in job
    steps:
      # Get code from repo
      - name: Checkout code
        uses: actions/checkout@v1
      # Install NodeJS
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      # Run npm install and build on our code
      - run: yarn install
      - run: yarn run build
        env:
          GRAPHCMS_PROJECT_API: ${{ secrets.GRAPHCMS_PROJECT_API }}
      # Deploy to Netlify using our production secrets
      - name: 🚀 Deploy to Netlify
        id: deploy-netlify
        uses: netlify/actions/cli@master
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        with:
          args: deploy --prod -m 'v${{ steps.package-version.outputs.current-version}} ・ ${{ github.head_ref }}'

  # if PR is closed without merging...
  close_job:
    # this job will only run if the PR has been closed without being merged
    if: github.event.pull_request.merged == false
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo PR #${{ github.event.number }} has been closed without being merged